apiVersion: v2
name: lgtm-stack
description: A Helm chart for Grafana Labs LGTM with kube-prometheus-stack、MinIO、Phlare
type: application
version: 0.1.0

appVersion: "0.1.0"

dependencies:
  - name: "kube-prometheus-stack"
    alias: kubeprometheusstack
    condition: kubeprometheusstack.enabled
    version: "~45.1.1"
    repository:  "https://prometheus-community.github.io/helm-charts"
  - name: loki-stack
    version: "~2.9.9"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki-stack.enabled
  - name: mimir-distributed
    version: "~4.0.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: mimir.enabled
    alias: mimir
  - name: tempo
    version: "~1.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: tempo.enabled
  - name: phlare
    version: "~0.1.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: phlare.enabled
  - alias: minio
    condition: minio.enabled
    name: minio
    repository: https://helm.min.io/
    version: "~8.0.10"