{{- if and .Values.tempo.enabled .Values.tempo.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tempo-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      access: proxy
      url: http://{{ .Release.Name }}-tempo:3100
      version: 1
      isDefault: false
      uid: tempo
{{- end }}
